services:
  db:
    image: postgres:16
    container_name: zivio_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zivio_db
      POSTGRES_USER: zivio_user
      POSTGRES_PASSWORD: zivio_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
